### ISSUE TITLE
sbu.framework didn't enable bitcode flag

### ISSUE THREAD

**Issue by chawatvish** [webex/webex-ios-sdk#41]
I can't build my project because sbu.framework didn't enable bitcode flag.
Can rebuild that framework with enable bitcode, please?

**Comment by EvgeniyGT** [comment]
+1

**Comment by EvgeniyGT** [comment]
Any updates here?

**Comment by chawatvish** [comment]
I think no update. TT BTW my project moved out from Webex bye~

**Comment by MrShiY** [comment]
Sorry, SDK doesn't support enabling bitcode for now.

**Comment by olivierproffit** [comment]
Hi @chawatvish @EvgeniyGT  we don't support bitcode on the mobile SDKs.
If it's important for your use case, feel free to go to our feature request tool https://ciscocollaboration.aha.io/session/new and vote if existing already otherwise create a new one.
Please make sure you document your expectations and your business case. This way, this feature request will go up in our priority list

**Comment by chawatvish** [comment]
Thank you all you guy for the information. @MrShiY @olivierproffit
