### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by hariel18** [webex/webex-ios-sdk#79]
Hello,
is Swift Package Manager support in your plans for the near future?

Thanx in advance.

**Comment by olivierproffit** [comment]
Hi @hariel18   Thanks for your feature request.
If it's important for your use case, could you use our feature request tool https://ciscocollaboration.aha.io/session/new and vote if existing already otherwise create a new one. 
Please make sure you document your expectations and your business case. This way, this feature request will go up in our priority list.
Closing this ticket as we track feature requests in Aha
